apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-api
  template:
    metadata:
      labels:
        app: ecom-api
    spec:
      containers:
      - name: ecom-api
        image: digdigdigdig/ecom-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-api-service
spec:
  selector:
    app: ecom-api
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
